services:
  app:
    image: ericstaedler/staerium-server:latest
    environment:
      - APP_NAME=StaeriumServer
    volumes:
      - ./configuration.sunproj:/app/src/myapp/config.xml:ro
    restart: unless-stopped
