services:
  StaeriumServer:
    image: ericstaedler/staerium-server:latest
    environment:
      - APP_NAME=StaeriumServer
      - DEBUG=False
    volumes:
      - ./configuration.sunproj:/app/src/myapp/config.xml:ro
    restart: unless-stopped
